# Generated by Django 4.2 on 2023-05-20 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_delete_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default=18, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_joined',
            field=models.TimeField(default=datetime.time(5, 53, 21, 897581)),
        ),
    ]
