# Generated by Django 4.2 on 2023-05-20 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_age_profile_time_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_joined',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
