# Generated by Django 4.2 on 2023-05-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_profile_time_joined_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
