# Generated by Django 4.2 on 2023-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_name',
            field=models.CharField(blank=True, default='Default File name', max_length=50),
        ),
    ]
