# Generated by Django 4.2 on 2023-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_profile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
