# Generated by Django 4.1.7 on 2023-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Brief_Content',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
