# Generated by Django 4.1.7 on 2023-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_post_brief_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category_Tag',
            field=models.CharField(default='Default', max_length=20),
        ),
    ]
