# Generated by Django 4.2 on 2023-07-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_post_thumbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbs',
            old_name='currentThumbs',
            new_name='current_thumbs',
        ),
    ]
