# Generated by Django 4.2 on 2023-07-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
