# Generated by Django 4.1.7 on 2023-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(default='Posts/Profile_Picture/Profile.png', upload_to='Posts/Profile_Picture/')),
            ],
        ),
    ]
