# Generated by Django 4.1.7 on 2023-04-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
