# Generated by Django 4.2 on 2023-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_delete_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='Comment',
        ),
    ]
