# Generated by Django 4.2 on 2023-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0013_remove_post_brief_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='First_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='Last_Name',
            field=models.CharField(max_length=15),
        ),
    ]
